### ISSUE TITLE
Documentation for the dataset

### ISSUE THREAD

**Issue by ereday** [klimzaporojets/TempEL#1]
Hi, thanks for making the dataset publicly available. I'm wondering if there is a documentation explaining what the keys within the json file are? To make it clear, I'm referring to the following set:

`dict_keys(['subset', 'category', 'current_snapshot', 'target_qid', 'target_page_id', 'target', 'target_bert', 'target_title', 'target_title_bert', 'target_len', 'mention', 'mention_bert', 'context_left', 'context_left_bert', 'context_right', 'context_right_bert', 'anchor_len', 'ed_men_title', 'ed_men_title_main', 'overlap_type', 'mention_prior', 'mention_prior_rank', 'avg_mention_prior', 'avg_mention_prior_rank', 'entity_prior', 'nr_inlinks', 'nr_dist_mentions', 'nr_mentions_per_ent', 'nr_mentions_extracted', 'anchor_creation_date', 'anchor_revision_date', 'target_creation_date', 'target_revision_date'])`

**EDIT:** If I understood correctly from  the explanation in the README, not all of the mentions of entities appearing in the articles in TempEL were annotated, right?

**EDIT:** Based on a quick look on the train.jsonl files, I understand that TempEL doesn't provide entity linking annotation (spans, entity assignment etc.) for all the mentions appearing in the articles, right?

**Comment by klimzaporojets** [comment]
Dear ereday, 

Thanks a lot for your interest in our work! 

We describe the meaning of the attributes in table 4 (p. 26) of our manuscript: https://arxiv.org/pdf/2302.02500.pdf .

You are right, not all the mentions in the document are annotated, we focus on harder mentions (e.g., low overlap with the title of entity, etc.) 

Hope this helps!, please let us know if you have any further questions :) 

Klim
